server:
  port: 8080
spring:
  application:
    name: javaee
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/javaee?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # RabbitMQ 配置
  rabbitmq:
    host: 192.168.111.100  # 你的RabbitMQ地址
    port: 5672       # 默认端口
    username: JavaEE  # 账号
    password: 12345  # 密码
    virtual-host: JavaEE  # 默认虚拟主机

    # QQ邮箱配置
  mail:
    host: smtp.qq.com  # QQ邮箱SMTP服务器
    username: 3232808626@qq.com  # 发送方QQ邮箱
    password: msxptkxapnzedadd  # QQ邮箱授权码（非登录密码）
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true